AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

require:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Max: 120

RSpec/NamedSubject:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Metrics/MethodLength:
  Max: 15

RSpec/NestedGroups:
  Max: 10

# Style/ClassAndModuleChildren:
#   EnforcedStyle: compact